### ISSUE TITLE
Dataview "link" function worked in 1.2.0, broken in 1.3.0

### ISSUE THREAD

**Issue by tijmenvdk** [dsebastien/obsidian-dataview-serializer#24]
In the earlier version, `link(file.link, title) AS "Story"` results in `[[Customers and projects/Customer stories/Northwind customer story.md|Northwind]]`, displaying as `Northwind`.

In the updated version, the result is `[[Northwind]]`, which results in a broken link.

**Comment by quantumgardener** [comment]
There is a fix in train for this. Changes made in 1.3.0 didn't account for cases where there was an alias different from the filename, which is what you have here. 

See #21

**Comment by dsebastien** [comment]
I'll release the update today

Le mer. 25 sept. 2024 à 11:15, quantumgardener ***@***.***> a
écrit :

**Comment by dsebastien** [comment]
Later than I hoped, but I've released 1.4.0 today. Closing this issue, assuming it's fixed, but don't hesitate to come back if not.
