### ISSUE TITLE
Installing Plugin

### ISSUE THREAD

**Issue by Quasaur** [dsebastien/obsidian-dataview-serializer#5]
Forgive me for being an idiot...but how exactly do i install this plugin???

**Comment by tijmenvdk** [comment]
Copy the .js, .json and .css files to a new folder under the `.obsidian\plugins` folder in your vault, restart Obsidian and enable the plugin in Obsidian settings.

**Comment by dsebastien** [comment]
Don't worry @Quasaur. The plugin should be in the official list of community plugins within a few weeks, it'll be much simpler at that point. For now, follow @tijmenvdk's instructions.
