### ISSUE TITLE
References to "this" do not appear to work

### ISSUE THREAD

**Issue by tijmenvdk** [dsebastien/obsidian-dataview-serializer#6]
The following query does not give any result:
`<!-- QueryToSerialize: LIST WITHOUT ID trainerFor from #talent where file.path = this.file.path -->`

whereas the dataview query does: 
`LIST WITHOUT ID trainerFor from #talent where file.path=this.file.path`

Replacing the "this" with an explicit path does work:
`<!-- QueryToSerialize: LIST WITHOUT ID trainerFor from #talent where file.path="Talent insights/Talent/geo/name.md" -->`

The "this" keyword is currently part of the template, would prefer to avoid having to update 200 files.

**Comment by tijmenvdk** [comment]
The same seems to apply to queries that use `[[]]` in the FROM statement: no results, but `[[current file]]` does work.

**Comment by dsebastien** [comment]
Indeed, I noticed that too. I think I know why. I did not provide the origin file when calling the Dataview queryMarkdown function: https://github.com/blacksmithgu/obsidian-dataview/blob/d05d6d6d5033c5b115420ac15532e1604bda39ef/src/api/inline-api.ts#L151

I guess doing so will fix the issue. I'll look at it this week

**Comment by dsebastien** [comment]
I've pushed version 1.1.4 to try and fix this. I now set the origin file correctly.
