### ISSUE TITLE
Can't get plugin to work

### ISSUE THREAD

**Issue by Kullenej** [dsebastien/obsidian-dataview-serializer#9]
Thank you for a very needed plugin!

Unfortunately, I can't get the plugin to work. I have added folders to scan and folders to ignore in the settings. Created a page with a dataview query and then used cmd+p and used the serializer-plugin but nothing happens. 

Tell me if you need some more details.

**Comment by dsebastien** [comment]
Hello,

Let's try and fix that. Can you share the text of the note where you have added the query?
Also, could you:
- Hit CTRL + SHIFT + I to open the developer tools
- Run the command again
- Share the output (if any) in the console?

This might help understanding what's going wrong.

**Comment by tijmenvdk** [comment]
When you say you have "created a page with a dataview query", did you create it as documented (iow, with the `<!-- QueryToSerialize: ` html comments)? When the plugin functions correctly, you do not have to cmd+p to kick off the serialization, it happens automatically (I believe whenever Obsidian writes the file to disk).

**Comment by dsebastien** [comment]
Yes, it's automatic when you modify a file that is part of the folders to scan and note in the ignore list.

Could you create/share a sample vault reproducing this issue?

**Comment by Kullenej** [comment]
Sorry, my fault! I didn't see the link to the documentation under Readme. So I didn't know about the HTML code that's needed. Sorry again, and consider this issue closed. :)

**Comment by dsebastien** [comment]
Great 👍
